Sistema/JapanoriWebSystem/Controllers/ComandaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JapanoriWebSystem.DAL;
using JapanoriWebSystem.Models;

namespace JapanoriWebSystem.Controllers
{
    public class ComandaController : Controller
    {
#pragma warning disable IDE0044 // Adicionar modificador somente leitura
        private JapanoriContext db = new JapanoriContext();
#pragma warning restore IDE0044 // Adicionar modificador somente leitura

        // GET: Comanda
        public ActionResult Index()
        {
            Database.SetInitializer(new DropCreateDatabaseAlways<JapanoriContext>());
            return View(db.Comandas.ToList());
        }

        // GET: Comanda/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comanda comanda = db.Comandas.Find(id);
            if (comanda == null)
            {
                return HttpNotFound();
            }
            return View(comanda);
        }

        // GET: Comanda/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Comanda/Create
        // Para proteger-se contra ataques de excesso de postagem, ative as propriedades específicas às quais deseja se associar. 
        // Para obter mais detalhes, confira https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Situacao,Status")] Comanda comanda)
        {
            if (ModelState.IsValid)
            {
                db.Comandas.Add(comanda);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(comanda);
        }

        // GET: Comanda/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comanda comanda = db.Comandas.Find(id);
            if (comanda == null)
            {
                return HttpNotFound();
            }
            return View(comanda);
        }

        // POST: Comanda/Edit/5
        // Para proteger-se contra ataques de excesso de postagem, ative as propriedades específicas às quais deseja se associar. 
        // Para obter mais detalhes, confira https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Situacao,Status")] Comanda comanda)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comanda).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(comanda);
        }

        // GET: Comanda/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comanda comanda = db.Comandas.Find(id);
            if (comanda == null)
            {
                return HttpNotFound();
            }
            return View(comanda);
        }

        // POST: Comanda/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comanda comanda = db.Comandas.Find(id);
            db.Comandas.Remove(comanda);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Sistema/JapanoriWebSystem/Controllers/ReservaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JapanoriWebSystem.Controllers
{
    public class ReservaController : Controller
    {
        // GET: Reserva
        public ActionResult Cadastro()
        {
            return View();
        }
    }
}

Sistema/JapanoriWebSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>

    @Styles.Render("~/Content/Site.css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Japanori", "Hub", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("Início", "Hub", "Home")
                    </li>
                    <li>
                        <a href="#">
                            Comanda
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Consultar", "Index", "Comanda")</li>
                            <li>@Html.ActionLink("Consultar", "Create", "Comanda")</li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">
                            Cadastro
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Reservas", "cadastroReserva", "Reserva")</li>
                            <li>@Html.ActionLink("Produto", "cadastroProduto", "Produto")</li>
                            <li>@Html.ActionLink("Fornecedor", "cadastroFornecedor", "Fornecedor")</li>
                            <li>@Html.ActionLink("Funcionário", "cadastroFuncionario", "Funcionario")</li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">
                            Consulta
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Reservas", "cadastroReserva", "Reserva")</li>
                            <li>@Html.ActionLink("Produto", "cadastroProduto", "Produto")</li>
                            <li>@Html.ActionLink("Fornecedor", "cadastroFornecedor", "Fornecedor")</li>
                            <li>@Html.ActionLink("Funcionário", "cadastroFuncionario", "Funcionario")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Sistema/JapanoriWebSystem/Views/Shared/_LayoutPrincipal.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Japanori", "Hub", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Hub", "Hub", "Home")</li>
                    <li>@Html.ActionLink("Comandas", "Index", "Comanda")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>

</body>
</html>